<template>
    <table class="payerTable">
        <thead>
            <tr>
                <th style="width: 18%">{{ langMap[lang].payerTime }}</th>
                <th style="width: 20%">{{ langMap[lang].payer }}</th>
                <th style="width: 14%">{{ langMap[lang].amount }}</th>
                <th style="width: 15%">{{ langMap[lang].way }}</th>
                <th style="width: 40%">{{ langMap[lang].remark }}</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="friend in friends" :key="friend.name">
                <td>{{ friend.time }}</td>
                <td>{{ friend.name }}</td>
                <td>{{ friend.amount }}</td>
                <td>{{ friend.way }}</td>
                <td>{{ friend.remark }}</td>
            </tr>
        </tbody>
    </table>
    <div class="updateTime">{{ langMap[lang].time }}2026-01-04 12:50:00</div>
</template>

<script setup lang="ts">
import { useData } from 'vitepress'

const vpData = useData()
const lang = vpData.lang.value

const langMap: any = {
    zh: {
        time: '最后更新时间：',
        payerTime: '赞助时间',
        payer: '赞助者',
        amount: '赞助金额',
        way: '赞助方式',
        remark: '留言内容',
    },
    en: {
        time: 'Last updated time: ',
        payerTime: 'Payer Time',
        payer: 'Payer',
        amount: 'Amount',
        way: 'Way',
        remark: 'Remark',
    },
}

const friends = [
    {
        name: '*悟',
        time: '2026-01-04',
        amount: '20',
        way: '微信',
        remark: '助PakePlus蒸蒸日上!赏金，一点诚意',
    },
    {
        name: '*)',
        time: '2026-01-01',
        amount: '50',
        way: '微信',
        remark: 'sensor****@gmail.com qibutao',
    },
    {
        name: '初～一',
        time: '2026-01-01',
        amount: '200',
        way: '微信',
        remark: '感谢作者，新年快乐🎉',
    },
    {
        name: '°°初阳°°',
        time: '2025-12-31',
        amount: '66.66',
        way: '微信',
        remark: '2025年的最后一天，支持一下！',
    },
    {
        name: '**Lover',
        time: '2025-12-30',
        amount: '100',
        way: '支付宝',
        remark: '提前祝作者元旦快乐',
    },
    {
        name: '成熟时🍇',
        time: '2025-12-28',
        amount: '20',
        way: '微信',
        remark: '项目很棒，继续加油',
    },
    {
        name: '*城',
        time: '2025-12-28',
        amount: '50',
        way: '支付宝',
        remark: '很有用的工具',
    },
    {
        name: '匿名用户',
        time: '2025-12-27',
        amount: '8.88',
        way: '微信',
        remark: '一点心意',
    },
    {
        name: '☁️云淡风轻',
        time: '2025-12-25',
        amount: '99',
        way: '微信',
        remark: '圣诞快乐，请你喝咖啡',
    },
    {
        name: '**运工',
        time: '2025-12-24',
        amount: '99',
        way: '支付宝',
        remark: '平安夜快乐',
    },
    {
        name: '橘*',
        time: '2025-12-22',
        amount: '50',
        way: '微信',
        remark: '支持开源',
    },
    {
        name: '**普',
        time: '2025-12-22',
        amount: '5.20',
        way: '支付宝',
        remark: '支持开源',
    },
    {
        name: '*长安',
        time: '2025-12-20',
        amount: '100',
        way: '支付宝',
        remark: '为PakePlus加油！',
    },
    {
        name: '秋意浓',
        time: '2025-12-19',
        amount: '166',
        way: '微信',
        remark: '非常感谢你的项目',
    },
    {
        name: 'Luna',
        time: '2025-12-18',
        amount: '9.9',
        way: '支付宝',
        remark: '好用！',
    },
    {
        name: '静候♡时光',
        time: '2025-12-16',
        amount: '88',
        way: '微信',
        remark: '祝项目越来越好',
    },
    {
        name: '**网友',
        time: '2025-12-16',
        amount: '66.66',
        way: '支付宝',
        remark: '很有启发',
    },
    {
        name: '墨染',
        time: '2025-12-13',
        amount: '6.66',
        way: '微信',
        remark: '谢谢你',
    },
    {
        name: '**虹',
        time: '2025-12-12',
        amount: '121.2',
        way: '支付宝',
        remark: '双12支持一波',
    },
    {
        name: '跳动**',
        time: '2025-12-11',
        amount: '50',
        way: '微信',
        remark: '期待更多功能',
    },
    {
        name: '**ite',
        time: '2025-12-09',
        amount: '100',
        way: '支付宝',
        remark: 'Respect',
    },
    {
        name: '听风※观雨',
        time: '2025-12-08',
        amount: '28.88',
        way: '微信',
        remark: '感谢开发',
    },
    {
        name: '**湖畔',
        time: '2025-12-08',
        amount: '66',
        way: '支付宝',
        remark: '好工具值得付费',
    },
    {
        name: '简单就好',
        time: '2025-12-05',
        amount: '20',
        way: '微信',
        remark: '很喜欢这个工具',
    },
    {
        name: '**星',
        time: '2025-12-04',
        amount: '50',
        way: '支付宝',
        remark: '小意思',
    },
    {
        name: '浪漫~',
        time: '2025-12-02',
        amount: '88',
        way: '微信',
        remark: '解决了我的大问题',
    },
    {
        name: '*轻',
        time: '2025-12-01',
        amount: '10',
        way: '支付宝',
        remark: '月初第一捐',
    },
    {
        name: '艺术人生',
        time: '2025-11-30',
        amount: '50',
        way: '微信',
        remark: '感谢大佬',
    },
    {
        name: '似水',
        time: '2025-11-28',
        amount: '6.66',
        way: '支付宝',
        remark: '支持一下',
    },
    {
        name: '楼台',
        time: '2025-11-27',
        amount: '100',
        way: '微信',
        remark: '非常优秀的开源项目',
    },
    {
        name: '**观云',
        time: '2025-11-27',
        amount: '45',
        way: '支付宝',
        remark: '加油开发',
    },
    {
        name: '追梦人',
        time: '2025-11-24',
        amount: '20',
        way: '微信',
        remark: '支持作者',
    },
    {
        name: '*天',
        time: '2025-11-23',
        amount: '50',
        way: '支付宝',
        remark: '我一定要支持你',
    },
    {
        name: '斜阳～～～',
        time: '2025-11-22',
        amount: '9.9',
        way: '微信',
        remark: '大爱',
    },
    {
        name: '**风',
        time: '2025-11-20',
        amount: '30',
        way: '支付宝',
        remark: '不错，挺顺手',
    },
    {
        name: '不凡',
        time: '2025-11-19',
        amount: '50',
        way: '微信',
        remark: '一直关注你的博客',
    },
    {
        name: '匿名～',
        time: '2025-11-18',
        amount: '88.8',
        way: '支付宝',
        remark: '发发发',
    },
    {
        name: '半只橙',
        time: '2025-11-16',
        amount: '15',
        way: '微信',
        remark: '好用，谢谢',
    },
    {
        name: '孤独的狼',
        time: '2025-11-15',
        amount: '50',
        way: '微信',
        remark: '支持原创',
    },
    {
        name: 'ChasLui',
        time: '2025-11-13',
        amount: '66',
        way: '微信',
        remark: '心情好，小意思',
    },
    {
        name: '**师',
        time: '2025-11-12',
        amount: '100',
        way: '微信',
        remark: '节省了我很多时间',
    },
    {
        name: 'Chris',
        time: '2025-11-11',
        amount: '11.11',
        way: '微信',
        remark: '双11快乐，祝越来越好',
    },
    {
        name: '**auk',
        time: '2025-11-11',
        amount: '20',
        way: '支付宝',
        remark: '加油作者',
    },
    {
        name: 'elyn🏠🚗🧸',
        time: '2025-11-08',
        amount: '50',
        way: '微信',
        remark: '期待新版本',
    },
    {
        name: '🍬糖果🍬',
        time: '2025-11-07',
        amount: '30',
        way: '微信',
        remark: '赞一个',
    },
    {
        name: '💞平凡之路',
        time: '2025-11-05',
        amount: '80',
        way: '微信',
        remark: '生产力工具a',
    },
    {
        name: '不知名路人',
        time: '2025-11-04',
        amount: '5',
        way: '微信',
        remark: '虽然不多但支持一下',
    },
    {
        name: '无忌',
        time: '2025-11-04',
        amount: '200',
        way: '微信',
        remark: '非常感谢你的付出',
    },
    {
        name: '*娜',
        time: '2025-11-01',
        amount: '50',
        way: '支付宝',
        remark: '好',
    },
    {
        name: 'S*r',
        time: '2025-10-30',
        amount: '38.8',
        way: '微信',
        remark: '学习一下',
    },
    {
        name: '**Sama',
        time: '2025-10-30',
        amount: '66',
        way: '支付宝',
        remark: '很有想法的项目',
    },
    {
        name: '匿名匿名',
        time: '2025-10-28',
        amount: '50',
        way: '微信',
        remark: '设计感很棒',
    },
    {
        name: '左手刘',
        time: '2025-10-27',
        amount: '30',
        way: '微信',
        remark: '支持好作品',
    },
    {
        name: 'O泡果奶ooo',
        time: '2025-10-25',
        amount: '25',
        way: '微信',
        remark: '反馈个小建议，在评论区说了',
    },
    {
        name: '你再对我笑！',
        time: '2025-10-24',
        amount: '50',
        way: '微信',
        remark: '支持大佬',
    },
    {
        name: '超皮',
        time: '2025-10-22',
        amount: '128',
        way: '微信',
        remark: '请吃火锅',
    },
    {
        name: '**爱',
        time: '2025-10-21',
        amount: '10',
        way: '支付宝',
        remark: '支持下',
    },
    {
        name: '卫宸源',
        time: '2025-10-20',
        amount: '20',
        way: '微信',
        remark: '加油加油',
    },
    {
        name: '匿名',
        time: '2025-10-18',
        amount: '50',
        way: '支付宝',
        remark: '好工具',
    },
    {
        name: 'Шилдэг',
        time: '2025-10-17',
        amount: '30',
        way: '微信',
        remark: '致敬技术',
    },
    {
        name: '*张',
        time: '2025-10-15',
        amount: '50',
        way: '支付宝',
        remark: '界面简洁，深得我心',
    },
    {
        name: '追求财富梦想！',
        time: '2025-10-11',
        amount: '6',
        way: '微信',
        remark: '赞赞赞',
    },
    {
        name: '诚信',
        time: '2025-10-09',
        amount: '50',
        way: '微信',
        remark: '感谢帮助',
    },
    {
        name: '平凡',
        time: '2025-10-06',
        amount: '88',
        way: '微信',
        remark: '很不错的一款产品',
    },
    {
        name: '学习使我快乐',
        time: '2025-10-05',
        amount: '50',
        way: '微信',
        remark: '值得收藏',
    },
    {
        name: '青尘sang',
        time: '2025-10-01',
        amount: '100',
        way: '支付宝',
        remark: '国庆快乐',
    },
    {
        name: '夏日清风',
        time: '2025-09-28',
        amount: '88',
        way: '微信',
        remark: '感谢开发这么好用的工具',
    },
    {
        name: '星辰',
        time: '2025-09-25',
        amount: '50',
        way: '支付宝',
        remark: '支持开源项目',
    },
    {
        name: '匿名~',
        time: '2025-09-20',
        amount: '66.66',
        way: '微信',
        remark: '请喝咖啡',
    },
    {
        name: '夏能啟',
        time: '2025-09-17',
        amount: '9.9',
        way: '微信',
        remark: '学到了很多，感谢',
    },
    {
        name: '技术小白',
        time: '2025-09-15',
        amount: '20',
        way: '微信',
        remark: '学到了很多，感谢',
    },
    {
        name: 'CodeLover',
        time: '2025-09-10',
        amount: '100',
        way: '支付宝',
        remark: '代码写得真棒',
    },
    {
        name: '年华',
        time: '2025-09-06',
        amount: '50',
        way: '微信',
        remark: '加油',
    },
    {
        name: '秋风',
        time: '2025-09-05',
        amount: '30',
        way: '微信',
        remark: '小小支持',
    },
    {
        name: '匿名~',
        time: '2025-08-28',
        amount: '199',
        way: '微信',
        remark: '为爱发电，加油',
    },
    {
        name: '开发者-Bryan',
        time: '2025-08-25',
        amount: '88.88',
        way: '支付宝',
        remark: '同行支持',
    },
    {
        name: '**华',
        time: '2025-08-25',
        amount: '50',
        way: '支付宝',
        remark: '同行支持',
    },
    {
        name: '连山',
        time: '2025-08-21',
        amount: '68',
        way: '微信',
        remark: '请喝下午茶',
    },
    {
        name: '学生党',
        time: '2025-08-20',
        amount: '10',
        way: '微信',
        remark: '虽然不多，一点心意',
    },
    {
        name: 'Dadong',
        time: '2025-08-15',
        amount: '68',
        way: '微信',
        remark: '工具很实用',
    },
    {
        name: '2025 [置顶朋友圈]',
        time: '2025-08-14',
        amount: '14.88',
        way: '微信',
        remark: '请喝下午茶',
    },
    {
        name: 'S****',
        time: '2025-08-10',
        amount: '58',
        way: '支付宝',
        remark: 'UI做得不错',
    },
    {
        name: '匿名~',
        time: '2025-08-05',
        amount: '33.33',
        way: '微信',
        remark: '随机支持一下',
    },
    {
        name: 'Huang',
        time: '2025-07-30',
        amount: '45',
        way: '微信',
        remark: '稳定性很好',
    },
    {
        name: '晌午',
        time: '2025-07-27',
        amount: '8.88',
        way: '微信',
        remark: '感谢大佬',
    },
    {
        name: '开源爱好者-Alan',
        time: '2025-07-25',
        amount: '77.77',
        way: '支付宝',
        remark: '支持开源精神',
    },
    {
        name: '吃的多',
        time: '2025-07-20',
        amount: '55.55',
        way: '微信',
        remark: '前端代码很优雅',
    },
    {
        name: '后端开发',
        time: '2025-07-15',
        amount: '66',
        way: '支付宝',
        remark: '架构设计得很好',
    },
    {
        name: '王磊',
        time: '2025-07-10',
        amount: '99.99',
        way: '微信',
        remark: '全栈项目典范',
    },
    {
        name: '吴彦*',
        time: '2025-07-08',
        amount: '28.88',
        way: '微信',
        remark: '部署很方便',
    },
    {
        name: '老张',
        time: '2025-07-05',
        amount: '120',
        way: '支付宝',
        remark: '数据处理功能强大',
    },
    {
        name: 'AI研究L',
        time: '2025-07-03',
        amount: '88',
        way: '微信',
        remark: '智能功能很实用',
    },
    {
        name: '匿名~',
        time: '2025-07-01',
        amount: '25',
        way: '微信',
        remark: '七月第一天来支持',
    },
    {
        name: '汤姆',
        time: '2025-06-18',
        amount: '99',
        way: '微信',
        remark: '小小意思，不成敬意',
    },
    {
        name: '🌱',
        time: '2025-06-16',
        amount: '10',
        way: '微信',
        remark: '赞助一下',
    },
    {
        name: '？',
        time: '2025-06-03',
        amount: '50',
        way: '微信',
        remark: '感谢老哥哈！',
    },
    {
        name: ': )',
        time: '2025-06-01',
        amount: '5',
        way: '微信',
        remark: '感谢帮助',
    },
    {
        name: 'Celia',
        time: '2025-05-30',
        amount: '200',
        way: '微信',
        remark: '正好找到你这个',
    },
    {
        name: '黄俊博@软件工程',
        time: '2025-05-30',
        amount: '66.66',
        way: '微信',
        remark: '感谢大佬(追加的赞助)',
    },
    {
        name: '黄俊博@软件工程',
        time: '2025-05-30',
        amount: '10',
        way: '支付宝',
        remark: '感谢大佬',
    },
    {
        name: '金楚轩',
        time: '2025-05-30',
        amount: '20',
        way: '微信',
        remark: '谢谢老师',
    },
    {
        name: '易经养生杜異田',
        time: '2025-05-29',
        amount: '10',
        way: '微信',
        remark: '感谢帮助',
    },
    {
        name: '要求匿名～',
        time: '2025-05-29',
        amount: '100',
        way: '微信',
        remark: '使用pakaplus很好用。能遇到个好工具不易',
    },
    {
        name: '阿崔cxr',
        time: '2025-05-26',
        amount: '200',
        way: '微信',
        remark: '😁PackPlus太好用啦😁过来赞助一波',
    },
    {
        name: 'ZHAO',
        time: '2025-05-18',
        amount: '20',
        way: '微信',
        remark: '请你喝杯咖啡',
    },
    {
        name: 'Dang',
        time: '2025-04-11',
        amount: '$30',
        way: 'Bitcoin',
        remark: '有web3钱包吗，给你赞助点',
    },
    {
        name: '*黏',
        time: '2025-04-05',
        amount: '88.88',
        way: '微信',
        remark: '感谢开源',
    },
    {
        name: '影阙คิดถึง',
        time: '2025-03-30',
        amount: '99',
        way: '微信',
        remark: '已赞赏，很实用',
    },
    {
        name: '匿名~',
        time: '2025-02-22',
        amount: '66',
        way: '微信',
        remark: '请大佬喝奶茶吧',
    },
    {
        name: '匿名~',
        time: '2025-02-22',
        amount: '66.66',
        way: '微信',
        remark: '感谢，基于你的项目，省事许多',
    },
    {
        name: '栗怀广',
        time: '2025-02-20',
        amount: '100',
        way: '微信',
        remark: '请大佬喝奶茶吧',
    },
    {
        name: '匿名~',
        time: '2024-12-09',
        amount: '10.00',
        way: '微信',
        remark: '请大佬喝奶茶吧',
    },
    {
        name: '匿名~',
        time: '2024-12-02',
        amount: '40.00',
        way: '微信',
        remark: '请大佬喝奶茶吧',
    },
    {
        name: '匿名~',
        time: '2024-11-29',
        amount: '99.00',
        way: '微信',
        remark: '为爱发电，开源不易',
    },
]
</script>

<style scoped>
.payerTable {
    width: 100%;
    border-collapse: collapse;
    /* border: 1px solid #000; */
}
</style>
