<template>
    <table>
        <tbody>
            <tr>
                <td>
                    DeepSeek
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/DeepSeek_0.0.1_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/DeepSeek_0.0.1_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/DeepSeek_0.0.1_amd64.deb"
                        >Linux</a
                    >
                </td>
                <td>
                    X (Twitter)
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Twitter/Twitter_0.0.1_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Twitter/Twitter_0.0.1_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Twitter/twitter_0.0.1_amd64.deb"
                        >Linux</a
                    >
                </td>
            </tr>
            <tr>
                <td>
                    <img
                    src=https://sjj1024.github.io/PakePlus/static/imgs/deepseek.png
                    width=600/>
                </td>
                <td>
                    <img
                    src=https://sjj1024.github.io/PakePlus/static/imgs/xtwitter.png
                    width=600/>
                </td>
            </tr>
            <tr>
                <td>
                    YouTube
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/YouTube/YouTube_0.0.2_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/YouTube/YouTube_0.0.2_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/YouTube/you-tube_0.0.2_amd64.deb"
                        >Linux</a
                    >
                </td>
                <td>
                    小红书
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/_0.0.1_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/_0.0.1_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://github.com/Sjj1024/PakePlus/releases/download/OtherFiles/_0.0.1_amd64.deb"
                        >Linux</a
                    >
                </td>
            </tr>
            <tr>
                <td>
                    <img
                    src=https://sjj1024.github.io/PakePlus/static/imgs/youtube.png
                    width=600/>
                </td>
                <td>
                    <img
                    src=https://sjj1024.github.io/PakePlus/static/imgs/hongshu.png
                    width=600/>
                </td>
            </tr>
            <tr>
                <td>
                    Tiktok
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Tiktok/Tiktok_0.0.2_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Tiktok/Tiktok_0.0.2_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://github.com/codegirle/PakePlus/releases/download/Tiktok/tiktok_0.0.2_amd64.deb"
                        >Linux</a
                    >
                </td>
                <td>
                    句乐部
                    <a
                        href="https://gh-proxy.com/github.com/cuixiaorui/PakePlus/releases/download/juleu/julebu_1.0.0_aarch64.dmg"
                        >Mac</a
                    >
                    <a
                        href="https://gh-proxy.com/github.com/cuixiaorui/PakePlus/releases/download/juleu/julebu_1.0.0_x64-setup.exe"
                        >Windows</a
                    >
                    <a
                        href="https://gh-proxy.com/github.com/cuixiaorui/PakePlus/releases/download/juleu/julebu_1.0.0_amd64.deb"
                        >Linux</a
                    >
                </td>
            </tr>
            <tr>
                <td>
                    <img
                    src=https://sjj1024.github.io/PakePlus/static/imgs/tiktok.png
                    width=600/>
                </td>
                <td>
                    <img src=https://files.pakeplus.com/julebu.webp width=600/>
                </td>
            </tr>
        </tbody>
    </table>

    <!-- 注意：这里需要添加一个免责声明 -->
    <p style="font-size: 16px; color: #999">
        注意：使用本软件时，请遵守相关法律法规，如果你使用github
        token使用本项目，默认会star本项目，并会统计项目编译结果是成功还是失败，用于改善项目和获取反馈。打包仅限个人使用，请勿传播或商业用途，打包资源会存储在你自己的Github开源仓库中，任何人都可以看得到，所以请严格遵守Github使用规范，否则后果自负。
    </p>
</template>

<script setup lang="ts">
// import { ref, reactive } from 'vue'
</script>

<style scoped lang="scss">
a {
    margin: 0 4px;
}
</style>
