let tauriConfig = {
    pattern: 'tauri',
    windows: {
        label: store.currentProject.name,
        url: store.currentProject.url,
        userAgent: platforms[store.currentProject.platform].userAgent,
        fileDropEnabled: true,
        center: true,
        x: 0,
        y: 0,
        width: store.currentProject.width,
        height: store.currentProject.height,
        minWidth: 400,
        minHeight: 300,
        maxWidth: 1000,
        maxHeight: 800,
        resizable: true,
        title: store.currentProject.showName,
        fullscreen: false,
        focus: true,
        transparent: false,
        maximized: false,
        visible: true,
        decorations: true,
        alwaysOnTop: false,
        contentProtected: false,
        skipTaskbar: false,
        theme: 'Light',
        titleBarStyle: 'Visible',
        hiddenTitle: false,
        acceptFirstMouse: true,
        tabbingIdentifier: '',
        additionalBrowserArgs: '',
    },
    cli: {
        description: '',
        longDescription: '',
        beforeHelp: '',
        afterHelp: '',
        args: [],
        subcommands: [],
    },
    bundle: {
        active: true,
        targets: [],
        identifier: '',
        publisher: '',
        icon: '',
        resources: '',
        copyright: '',
        category: '',
        shortDescription: '',
        longDescription: '',
        appimage: {
            bundleMediaFramework: false,
        },
        deb: {
            compression: 'none',
        },
        macOS: {
            frameworks: [],
            minimumSystemVersion: '',
            exceptionDomain: '',
            license: '',
            signingIdentity: '',
            providerShortName: '',
            entitlements: '',
        },
        externalBin: [],
        windows: {
            digestAlgorithm: '',
            certificateThumbprint: '',
            timestampUrl: '',
            tsp: '',
            webviewInstallMode: '',
            webviewFixedRuntimePath: '',
            allowDowngrades: false,
            wix: {
                language: '',
                template: '',
                skipWebviewInstall: false,
                license: '',
                enableElevatedUpdateTask: false,
                bannerPath: '',
                dialogImagePath: '',
            },
            nsis: {
                license: '',
                headerImage: '',
                sidebarImage: '',
                installerIcon: '',
                installMode: '',
                languages: '',
                displayLanguageSelector: false,
            },
        },
        allowlist: {
            all: false,
            fs: {
                scope: [],
                all: false,
                readFile: false,
                writeFile: false,
                readDir: false,
                writeDir: false,
                copyFile: false,
                createDir: false,
                removeDir: false,
                removeFile: false,
                renameFile: false,
                exists: false,
            },
            window: {
                all: false,
                create: false,
                center: false,
                requestUserAttention: false,
                setResizable: false,
                setTitle: false,
                maximize: false,
                unmaximize: false,
                minimize: false,
                unminimize: false,
                show: false,
                hide: false,
                close: false,
                setDecorations: false,
                setAlwaysOnTop: false,
                setContentProtected: false,
                setSize: false,
                setMinSize: false,
                setMaxSize: false,
                setPosition: false,
                setFullscreen: false,
                setFocus: false,
                setIcon: false,
                setSkipTaskbar: false,
                setCursorGrab: false,
                setCursorVisible: false,
                setCursorIcon: false,
                setCursorPosition: false,
                setIgnoreCursorEvents: false,
                startDragging: false,
                print: false,
            },
            shell: {
                scope: [],
                all: false,
                execute: false,
                sidecar: false,
                open: false,
            },
            dialog: {
                all: false,
                open: false,
                save: false,
                message: false,
                ask: false,
                confirm: false,
            },
            http: {
                scope: [],
                all: false,
                request: false,
            },
            notification: {
                all: false,
            },
            globalShortcut: {
                all: false,
            },
            os: {
                all: false,
            },
            path: {
                all: false,
            },
            protocol: {
                assetScope: [],
                all: false,
                asset: false,
            },
            process: {
                all: false,
                relaunch: false,
                relaunchDangerousAllowSymlinkMacos: false,
                exit: false,
            },
            clipboard: {
                all: false,
                writeText: false,
                readText: false,
            },
            app: {
                all: false,
                show: false,
                hide: false,
            },
        },
        security: {
            csp: '',
        },
        updater: {
            active: false,
            dialog: false,
            endpoints: [],
            pubkey: '',
            windows: {
                installerArgs: '',
                installMode: '',
            },
        },
        systemTray: {
            iconPath: '',
            iconAsTemplate: false,
            menuOnLeftClick: false,
            title: '',
        },
    },
}
